# Generated by Django 3.2 on 2023-03-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20230309_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=253, unique=True, verbose_name='E-mail'),
        ),
        migrations.DeleteModel(
            name='GenreTitle',
        ),
    ]
